### ISSUE TITLE
Deploying App to Predix cloud

### ISSUE THREAD

**Issue by mgit7** [predixdesignsystem/px-sample-app-react-directions#1]
How do I deploy this app to Predix cloud? I am able to run it locally without a problem but I am having trouble trying to figure out how to deploy it to the cloud. Any help is greatly appreciated!

Error is below:

>  2018-04-02T23:52:31.76-0700 [API/1] OUT Updated app with guid 7455ebd8-c0b0-4768-b9d6-c7083ab6a740 ({"name"=>"mgsdsu-predix-nodejs-starter", "command"=>"PRIVATE DATA HIDDEN", "memory"=>128, "buildpack"=>"nodejs_buildpack", "environment_json"=>"PRIVATE DATA HIDDEN"})
   2018-04-02T23:57:31.02-0700 [DEA/158] OUT Got staging request for app with id 7455ebd8-c0b0-4768-b9d6-c7083ab6a740
   2018-04-02T23:57:37.00-0700 [API/9] OUT Updated app with guid 7455ebd8-c0b0-4768-b9d6-c7083ab6a740 ({"state"=>"STARTED"})
   2018-04-02T23:57:40.37-0700 [STG/158] OUT -----> Downloaded app package (59M)
   2018-04-02T23:57:41.92-0700 [STG/158] OUT -----> Downloaded app buildpack cache (44M)
   2018-04-02T23:57:44.60-0700 [STG/0] OUT     -------> Buildpack version 1.5.29
   2018-04-02T23:57:44.63-0700 [STG/0] OUT -----> Creating runtime environment
   2018-04-02T23:57:44.63-0700 [STG/0] OUT        NPM_CONFIG_LOGLEVEL=error
   2018-04-02T23:57:44.63-0700 [STG/0] OUT        NPM_CONFIG_PRODUCTION=true
   2018-04-02T23:57:44.64-0700 [STG/0] OUT        NODE_VERBOSE=false
   2018-04-02T23:57:44.64-0700 [STG/0] OUT        NODE_ENV=production
   2018-04-02T23:57:44.64-0700 [STG/0] OUT        NODE_MODULES_CACHE=true
   2018-04-02T23:57:44.64-0700 [STG/0] OUT -----> Installing binaries
   2018-04-02T23:57:44.65-0700 [STG/0] OUT        engines.node (package.json):  >=6
   2018-04-02T23:57:44.65-0700 [STG/0] OUT        engines.npm (package.json):   >=4
   2018-04-02T23:57:44.82-0700 [STG/0] OUT        Downloading and installing node 7.5.0...
   2018-04-02T23:57:45.03-0700 [STG/0] OUT        WARNING: node 7 will no longer be available in new buildpacks released after 2017-06-30
   2018-04-02T23:57:45.03-0700 [STG/0] OUT        Downloaded [file:///var/vcap/data/dea_next/admin_buildpacks/a650821a-7cdd-4c2e-a81f-3453412f30a3_484b714a19dde2c8020f535def648881bd3cc90cbba9779639687f892291b9ab/dependencies/https___buildpacks.cloudfoundry.org_dependencies_node_node-7.5.0-linux-x64-73326a18.tgz]
   2018-04-02T23:57:45.85-0700 [STG/0] OUT        Downloading and installing npm >=4 (replacing version 4.1.2)...
   2018-04-02T23:58:01.18-0700 [STG/0] OUT        Downloading and installing yarn (0.20.0)...
   2018-04-02T23:58:01.35-0700 [STG/0] OUT        Downloaded [file:///var/vcap/data/dea_next/admin_buildpacks/a650821a-7cdd-4c2e-a81f-3453412f30a3_484b714a19dde2c8020f535def648881bd3cc90cbba9779639687f892291b9ab/dependencies/https___buildpacks.cloudfoundry.org_dependencies_yarn_yarn-v0.20.0-12df75bd.tar.gz]
   2018-04-02T23:58:01.81-0700 [STG/0] OUT        Installed yarn 0.20.0
   2018-04-02T23:58:01.81-0700 [STG/0] OUT -----> Restoring cache
   2018-04-02T23:58:02.22-0700 [STG/0] OUT        Skipping cache restore (new runtime signature)
   2018-04-02T23:58:02.22-0700 [STG/0] OUT -----> Building dependencies
   2018-04-02T23:58:02.23-0700 [STG/0] OUT        Installing node modules (yarn.lock)
   2018-04-02T23:58:02.23-0700 [STG/0] OUT        Running yarn in online mode
   2018-04-02T23:58:02.23-0700 [STG/0] OUT        To run yarn in offline mode, see: https://yarnpkg.com/blog/2016/11/24/offline-mirror
   2018-04-02T23:58:02.42-0700 [STG/0] OUT        yarn install v0.20.0
   2018-04-02T23:58:02.60-0700 [STG/0] OUT        [1/4] Resolving packages...
   2018-04-02T23:58:03.20-0700 [STG/0] OUT        [2/4] Fetching packages...
   2018-04-02T23:58:14.78-0700 [STG/0] OUT        warning fsevents@1.1.2: The platform "linux" is incompatible with this module.
   2018-04-02T23:58:14.78-0700 [STG/0] OUT        info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
   2018-04-02T23:58:14.78-0700 [STG/0] OUT        [3/4] Linking dependencies...
   2018-04-02T23:58:24.04-0700 [STG/0] OUT        [4/4] Building fresh packages...
   2018-04-02T23:58:24.25-0700 [STG/0] OUT        Done in 21.84s.
   2018-04-02T23:58:36.44-0700 [STG/0] ERR     warning fsevents@1.1.2: The platform "linux" is incompatible with this module.
   2018-04-02T23:58:38.21-0700 [STG/0] OUT        yarn.lock and package.json match
   2018-04-02T23:58:38.22-0700 [STG/0] OUT -----> Caching build
   2018-04-02T23:58:38.23-0700 [STG/0] OUT        Clearing previous node cache
   2018-04-02T23:58:38.89-0700 [STG/0] OUT        Saving 3 cacheDirectories (default):
   2018-04-02T23:58:38.89-0700 [STG/0] OUT        - .npm (nothing to cache)
   2018-04-02T23:58:38.89-0700 [STG/0] OUT        - .cache/yarn
   2018-04-02T23:58:41.88-0700 [STG/0] OUT -----> Build succeeded!
   2018-04-02T23:58:54.05-0700 [STG/158] OUT -----> Uploading droplet (77M)
   2018-04-02T23:59:07.84-0700 [DEA/158] OUT Starting app instance (index 0) with guid 7455ebd8-c0b0-4768-b9d6-c7083ab6a740
   **2018-04-02T23:59:25.19-0700 [App/0] ERR     module.js:472
   2018-04-02T23:59:25.19-0700 [App/0] ERR     ^
   2018-04-02T23:59:25.19-0700 [App/0] ERR Error: Cannot find module '/home/vcap/app/server/app.js'
   2018-04-02T23:59:25.19-0700 [App/0] ERR     at Function.Module._resolveFilename (module.js:470:15)
   2018-04-02T23:59:25.19-0700 [App/0] ERR     at Function.Module._load (module.js:418:25)
   2018-04-02T23:59:25.19-0700 [App/0] ERR     at Module.runMain (module.js:605:10)
   2018-04-02T23:59:25.19-0700 [App/0] ERR     at run (bootstrap_node.js:418:7)
   2018-04-02T23:59:25.19-0700 [App/0] ERR     at startup (bootstrap_node.js:139:9)
   2018-04-02T23:59:25.19-0700 [App/0] ERR     at bootstrap_node.js:533:3
   2018-04-02T23:59:25.19-0700 [App/0] OUT
   2018-04-02T23:59:25.21-0700 [DEA/158] ERR Instance (index 0) failed to start accepting connections**
   2018-04-02T23:59:25.21-0700 [API/10] OUT App instance exited with guid 7455ebd8-c0b0-4768-b9d6-c7083ab6a740 payload: {"cc_partition"=>"default", "droplet"=>"7455ebd8-c0b0-4768-b9d6-c7083ab6a740", "version"=>"9739eb17-dd08-4893-8b43-f9f1a7cc2c6f", "instance"=>"52f686316562404caf072d9610849995", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1522738765}
   2018-04-02T23:59:25.22-0700 [API/5] OUT App instance exited with guid 7455ebd8-c0b0-4768-b9d6-c7083ab6a740 payload: {"cc_partition"=>"default", "droplet"=>"7455ebd8-c0b0-4768-b9d6-c7083ab6a740", "version"=>"9739eb17-dd08-4893-8b43-f9f1a7cc2c6f", "instance"=>"52f686316562404caf072d9610849995", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1522738765}

**Comment by mdwragg** [comment]
Closing as dupilcate of https://github.com/predixdesignsystem/px-sample-app-react/issues/2
